import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('iris_data.csv')
print(df['SepalWidthCm'])
print('listed widths: ', list(df['SepalWidthCm']))
a=list(df['SepalLengthCm'])
b=list(df['SepalWidthCm'])
c=list(df['PetalLengthCm'])
d=list(df['PetalWidthCm'])
fig = plt.figure(figsize = (16,9))
ax1 = fig.add_subplot(611)
ax2 = fig.add_subplot(612)
ax3 = fig.add_subplot(613)
ax4 = fig.add_subplot(614)
ax5 = fig.add_subplot(615)
ax6 = fig.add_subplot(616)
ax1.plot(a,b)
ax2.plot(a,c)
ax3.plot(a,d)
ax4.plot(b,c)
ax5.plot(b,d)
ax6.plot(c,b)
plt.show()
plt.savefig('iris.graph.png', dpi=300)
